package winnu.dao;

import java.math.BigDecimal;
import java.sql.Connection;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.Date;
import java.util.Iterator;
import java.util.LinkedList;
import java.util.List;

import org.apache.torque.NoRowsException;
import org.apache.torque.TooManyRowsException;
import org.apache.torque.Torque;
import org.apache.torque.TorqueException;
import org.apache.torque.map.MapBuilder;
import org.apache.torque.map.TableMap;
import org.apache.torque.om.DateKey;
import org.apache.torque.om.NumberKey;
import org.apache.torque.om.StringKey;
import org.apache.torque.om.ObjectKey;
import org.apache.torque.om.SimpleKey;
import org.apache.torque.util.BasePeer;
import org.apache.torque.util.Criteria;

import com.workingdogs.village.DataSetException;
import com.workingdogs.village.QueryDataSet;
import com.workingdogs.village.Record;

// Local classes
import winnu.dao.map.*;


  
  
  
  
/**
 * This class was autogenerated by Torque on:
 *
 * [Sun Mar 21 16:07:34 CST 2010]
 *
 */
public abstract class BaseWithdrawnItemPeer
    extends BasePeer
{

    /** the default database name for this class */
    public static final String DATABASE_NAME = "winnudb";

     /** the table name for this class */
    public static final String TABLE_NAME = "WithdrawnItem";

    /**
     * @return the map builder for this peer
     * @throws TorqueException Any exceptions caught during processing will be
     *         rethrown wrapped into a TorqueException.
     */
    public static MapBuilder getMapBuilder()
        throws TorqueException
    {
        return getMapBuilder(WithdrawnItemMapBuilder.CLASS_NAME);
    }

      /** the column name for the WITHDRAWNITEMID field */
    public static final String WITHDRAWNITEMID;
      /** the column name for the SELLINGPRICE field */
    public static final String SELLINGPRICE;
      /** the column name for the DATEWITHDRAWN field */
    public static final String DATEWITHDRAWN;
      /** the column name for the REASON field */
    public static final String REASON;
      /** the column name for the QUANTITY field */
    public static final String QUANTITY;
      /** the column name for the DOCTORID field */
    public static final String DOCTORID;
      /** the column name for the SALEID field */
    public static final String SALEID;
      /** the column name for the ITEMBATCHID field */
    public static final String ITEMBATCHID;
      /** the column name for the USERID field */
    public static final String USERID;
  
    static
    {
          WITHDRAWNITEMID = "WithdrawnItem.WITHDRAWNITEMID";
          SELLINGPRICE = "WithdrawnItem.SELLINGPRICE";
          DATEWITHDRAWN = "WithdrawnItem.DATEWITHDRAWN";
          REASON = "WithdrawnItem.REASON";
          QUANTITY = "WithdrawnItem.QUANTITY";
          DOCTORID = "WithdrawnItem.DOCTORID";
          SALEID = "WithdrawnItem.SALEID";
          ITEMBATCHID = "WithdrawnItem.ITEMBATCHID";
          USERID = "WithdrawnItem.USERID";
          if (Torque.isInit())
        {
            try
            {
                getMapBuilder(WithdrawnItemMapBuilder.CLASS_NAME);
            }
            catch (Exception e)
            {
                log.error("Could not initialize Peer", e);
            }
        }
        else
        {
            Torque.registerMapBuilder(WithdrawnItemMapBuilder.CLASS_NAME);
        }
    }
 
    /** number of columns for this peer */
    public static final int numColumns =  9;

    /** A class that can be returned by this peer. */
    protected static final String CLASSNAME_DEFAULT =
        "winnu.dao.WithdrawnItem";

    /** A class that can be returned by this peer. */
    protected static final Class CLASS_DEFAULT = initClass(CLASSNAME_DEFAULT);

    /**
     * Class object initialization method.
     *
     * @param className name of the class to initialize
     * @return the initialized class
     */
    private static Class initClass(String className)
    {
        Class c = null;
        try
        {
            c = Class.forName(className);
        }
        catch (Throwable t)
        {
            log.error("A FATAL ERROR has occurred which should not "
                + "have happened under any circumstance.  Please notify "
                + "the Torque developers <torque-dev@db.apache.org> "
                + "and give as many details as possible (including the error "
                + "stack trace).", t);

            // Error objects should always be propogated.
            if (t instanceof Error)
            {
                throw (Error) t.fillInStackTrace();
            }
        }
        return c;
    }

    /**
     * Get the list of objects for a ResultSet.  Please not that your
     * resultset MUST return columns in the right order.  You can use
     * getFieldNames() in BaseObject to get the correct sequence.
     *
     * @param results the ResultSet
     * @return the list of objects
     * @throws TorqueException Any exceptions caught during processing will be
     *         rethrown wrapped into a TorqueException.
     */
    public static List resultSet2Objects(java.sql.ResultSet results)
            throws TorqueException
    {
        try
        {
            QueryDataSet qds = null;
            List rows = null;
            try
            {
                qds = new QueryDataSet(results);
                rows = getSelectResults(qds);
            }
            finally
            {
                if (qds != null)
                {
                    qds.close();
                }
            }

            return populateObjects(rows);
        }
        catch (SQLException e)
        {
            throw new TorqueException(e);
        }
        catch (DataSetException e)
        {
            throw new TorqueException(e);
        }
    }


  
    /**
     * Method to do inserts.
     *
     * @param criteria object used to create the INSERT statement.
     * @throws TorqueException Any exceptions caught during processing will be
     *         rethrown wrapped into a TorqueException.
     */
    public static ObjectKey doInsert(Criteria criteria)
        throws TorqueException
    {
        return BaseWithdrawnItemPeer
            .doInsert(criteria, (Connection) null);
    }

    /**
     * Method to do inserts.  This method is to be used during a transaction,
     * otherwise use the doInsert(Criteria) method.  It will take care of
     * the connection details internally.
     *
     * @param criteria object used to create the INSERT statement.
     * @param con the connection to use
     * @throws TorqueException Any exceptions caught during processing will be
     *         rethrown wrapped into a TorqueException.
     */
    public static ObjectKey doInsert(Criteria criteria, Connection con)
        throws TorqueException
    {
                                                        
        // Set the correct dbName if it has not been overridden
        // criteria.getDbName will return the same object if not set to
        // another value so == check is okay and faster
        if (criteria.getDbName() == Torque.getDefaultDB())
        {
            criteria.setDbName(DATABASE_NAME);
        }
        if (con == null)
        {
            return BasePeer.doInsert(criteria);
        }
        else
        {
            return BasePeer.doInsert(criteria, con);
        }
    }

    /**
     * Add all the columns needed to create a new object.
     *
     * @param criteria object containing the columns to add.
     * @throws TorqueException Any exceptions caught during processing will be
     *         rethrown wrapped into a TorqueException.
     */
    public static void addSelectColumns(Criteria criteria)
            throws TorqueException
    {
          criteria.addSelectColumn(WITHDRAWNITEMID);
          criteria.addSelectColumn(SELLINGPRICE);
          criteria.addSelectColumn(DATEWITHDRAWN);
          criteria.addSelectColumn(REASON);
          criteria.addSelectColumn(QUANTITY);
          criteria.addSelectColumn(DOCTORID);
          criteria.addSelectColumn(SALEID);
          criteria.addSelectColumn(ITEMBATCHID);
          criteria.addSelectColumn(USERID);
      }

    /**
     * Create a new object of type cls from a resultset row starting
     * from a specified offset.  This is done so that you can select
     * other rows than just those needed for this object.  You may
     * for example want to create two objects from the same row.
     *
     * @throws TorqueException Any exceptions caught during processing will be
     *         rethrown wrapped into a TorqueException.
     */
    public static WithdrawnItem row2Object(Record row,
                                             int offset,
                                             Class cls)
        throws TorqueException
    {
        try
        {
            WithdrawnItem obj = (WithdrawnItem) cls.newInstance();
            WithdrawnItemPeer.populateObject(row, offset, obj);
                  obj.setModified(false);
              obj.setNew(false);

            return obj;
        }
        catch (InstantiationException e)
        {
            throw new TorqueException(e);
        }
        catch (IllegalAccessException e)
        {
            throw new TorqueException(e);
        }
    }

    /**
     * Populates an object from a resultset row starting
     * from a specified offset.  This is done so that you can select
     * other rows than just those needed for this object.  You may
     * for example want to create two objects from the same row.
     *
     * @throws TorqueException Any exceptions caught during processing will be
     *         rethrown wrapped into a TorqueException.
     */
    public static void populateObject(Record row,
                                      int offset,
                                      WithdrawnItem obj)
        throws TorqueException
    {
        try
        {
                obj.setWithdrawnItemId(row.getValue(offset + 0).asInt());
                  obj.setSellingPrice(row.getValue(offset + 1).asDouble());
                  obj.setDateWithdrawn(row.getValue(offset + 2).asString());
                  obj.setReason(row.getValue(offset + 3).asString());
                  obj.setQuantity(row.getValue(offset + 4).asInt());
                  obj.setDoctorId(row.getValue(offset + 5).asInt());
                  obj.setSaleId(row.getValue(offset + 6).asInt());
                  obj.setItemBatchId(row.getValue(offset + 7).asInt());
                  obj.setUserId(row.getValue(offset + 8).asInt());
              }
        catch (DataSetException e)
        {
            throw new TorqueException(e);
        }
    }

    /**
     * Method to do selects.
     *
     * @param criteria object used to create the SELECT statement.
     * @return List of selected Objects
     * @throws TorqueException Any exceptions caught during processing will be
     *         rethrown wrapped into a TorqueException.
     */
    public static List doSelect(Criteria criteria) throws TorqueException
    {
        return populateObjects(doSelectVillageRecords(criteria));
    }

    /**
     * Method to do selects within a transaction.
     *
     * @param criteria object used to create the SELECT statement.
     * @param con the connection to use
     * @return List of selected Objects
     * @throws TorqueException Any exceptions caught during processing will be
     *         rethrown wrapped into a TorqueException.
     */
    public static List doSelect(Criteria criteria, Connection con)
        throws TorqueException
    {
        return populateObjects(doSelectVillageRecords(criteria, con));
    }

    /**
     * Grabs the raw Village records to be formed into objects.
     * This method handles connections internally.  The Record objects
     * returned by this method should be considered readonly.  Do not
     * alter the data and call save(), your results may vary, but are
     * certainly likely to result in hard to track MT bugs.
     *
     * @throws TorqueException Any exceptions caught during processing will be
     *         rethrown wrapped into a TorqueException.
     */
    public static List doSelectVillageRecords(Criteria criteria)
        throws TorqueException
    {
        return BaseWithdrawnItemPeer
            .doSelectVillageRecords(criteria, (Connection) null);
    }

    /**
     * Grabs the raw Village records to be formed into objects.
     * This method should be used for transactions
     *
     * @param con the connection to use
     * @throws TorqueException Any exceptions caught during processing will be
     *         rethrown wrapped into a TorqueException.
     */
    public static List doSelectVillageRecords(Criteria criteria, Connection con)
        throws TorqueException
    {
        if (criteria.getSelectColumns().size() == 0)
        {
            addSelectColumns(criteria);
        }

                                                        
        // Set the correct dbName if it has not been overridden
        // criteria.getDbName will return the same object if not set to
        // another value so == check is okay and faster
        if (criteria.getDbName() == Torque.getDefaultDB())
        {
            criteria.setDbName(DATABASE_NAME);
        }
        // BasePeer returns a List of Value (Village) arrays.  The array
        // order follows the order columns were placed in the Select clause.
        if (con == null)
        {
            return BasePeer.doSelect(criteria);
        }
        else
        {
            return BasePeer.doSelect(criteria, con);
        }
    }

    /**
     * The returned List will contain objects of the default type or
     * objects that inherit from the default.
     *
     * @throws TorqueException Any exceptions caught during processing will be
     *         rethrown wrapped into a TorqueException.
     */
    public static List populateObjects(List records)
        throws TorqueException
    {
        List results = new ArrayList(records.size());

        // populate the object(s)
        for (int i = 0; i < records.size(); i++)
        {
            Record row = (Record) records.get(i);
              results.add(WithdrawnItemPeer.row2Object(row, 1,
                WithdrawnItemPeer.getOMClass()));
          }
        return results;
    }
 

    /**
     * The class that the Peer will make instances of.
     * If the BO is abstract then you must implement this method
     * in the BO.
     *
     * @throws TorqueException Any exceptions caught during processing will be
     *         rethrown wrapped into a TorqueException.
     */
    public static Class getOMClass()
        throws TorqueException
    {
        return CLASS_DEFAULT;
    }

    /**
     * Method to do updates.
     *
     * @param criteria object containing data that is used to create the UPDATE
     *        statement.
     * @throws TorqueException Any exceptions caught during processing will be
     *         rethrown wrapped into a TorqueException.
     */
    public static void doUpdate(Criteria criteria) throws TorqueException
    {
         BaseWithdrawnItemPeer
            .doUpdate(criteria, (Connection) null);
    }

    /**
     * Method to do updates.  This method is to be used during a transaction,
     * otherwise use the doUpdate(Criteria) method.  It will take care of
     * the connection details internally.
     *
     * @param criteria object containing data that is used to create the UPDATE
     *        statement.
     * @param con the connection to use
     * @throws TorqueException Any exceptions caught during processing will be
     *         rethrown wrapped into a TorqueException.
     */
    public static void doUpdate(Criteria criteria, Connection con)
        throws TorqueException
    {
        Criteria selectCriteria = new Criteria(DATABASE_NAME, 2);
                   selectCriteria.put(WITHDRAWNITEMID, criteria.remove(WITHDRAWNITEMID));
                                                                                      
        // Set the correct dbName if it has not been overridden
        // criteria.getDbName will return the same object if not set to
        // another value so == check is okay and faster
        if (criteria.getDbName() == Torque.getDefaultDB())
        {
            criteria.setDbName(DATABASE_NAME);
        }
        if (con == null)
        {
            BasePeer.doUpdate(selectCriteria, criteria);
        }
        else
        {
            BasePeer.doUpdate(selectCriteria, criteria, con);
        }
    }

    /**
     * Method to do deletes.
     *
     * @param criteria object containing data that is used DELETE from database.
     * @throws TorqueException Any exceptions caught during processing will be
     *         rethrown wrapped into a TorqueException.
     */
     public static void doDelete(Criteria criteria) throws TorqueException
     {
         BaseWithdrawnItemPeer
            .doDelete(criteria, (Connection) null);
     }

    /**
     * Method to do deletes.  This method is to be used during a transaction,
     * otherwise use the doDelete(Criteria) method.  It will take care of
     * the connection details internally.
     *
     * @param criteria object containing data that is used DELETE from database.
     * @param con the connection to use
     * @throws TorqueException Any exceptions caught during processing will be
     *         rethrown wrapped into a TorqueException.
     */
     public static void doDelete(Criteria criteria, Connection con)
        throws TorqueException
     {
                                                        
        // Set the correct dbName if it has not been overridden
        // criteria.getDbName will return the same object if not set to
        // another value so == check is okay and faster
        if (criteria.getDbName() == Torque.getDefaultDB())
        {
            criteria.setDbName(DATABASE_NAME);
        }
        if (con == null)
        {
            BasePeer.doDelete(criteria);
        }
        else
        {
            BasePeer.doDelete(criteria, con);
        }
     }

    /**
     * Method to do selects
     *
     * @throws TorqueException Any exceptions caught during processing will be
     *         rethrown wrapped into a TorqueException.
     */
    public static List doSelect(WithdrawnItem obj) throws TorqueException
    {
        return doSelect(buildCriteria(obj));
    }

    /**
     * Method to do inserts
     *
     * @throws TorqueException Any exceptions caught during processing will be
     *         rethrown wrapped into a TorqueException.
     */
    public static void doInsert(WithdrawnItem obj) throws TorqueException
    {
          obj.setPrimaryKey(doInsert(buildCriteria(obj)));
          obj.setNew(false);
        obj.setModified(false);
    }

    /**
     * @param obj the data object to update in the database.
     * @throws TorqueException Any exceptions caught during processing will be
     *         rethrown wrapped into a TorqueException.
     */
    public static void doUpdate(WithdrawnItem obj) throws TorqueException
    {
        doUpdate(buildCriteria(obj));
        obj.setModified(false);
    }

    /**
     * @param obj the data object to delete in the database.
     * @throws TorqueException Any exceptions caught during processing will be
     *         rethrown wrapped into a TorqueException.
     */
    public static void doDelete(WithdrawnItem obj) throws TorqueException
    {
        doDelete(buildCriteria(obj));
    }

    /**
     * Method to do inserts.  This method is to be used during a transaction,
     * otherwise use the doInsert(WithdrawnItem) method.  It will take
     * care of the connection details internally.
     *
     * @param obj the data object to insert into the database.
     * @param con the connection to use
     * @throws TorqueException Any exceptions caught during processing will be
     *         rethrown wrapped into a TorqueException.
     */
    public static void doInsert(WithdrawnItem obj, Connection con)
        throws TorqueException
    {
          obj.setPrimaryKey(doInsert(buildCriteria(obj), con));
          obj.setNew(false);
        obj.setModified(false);
    }

    /**
     * Method to do update.  This method is to be used during a transaction,
     * otherwise use the doUpdate(WithdrawnItem) method.  It will take
     * care of the connection details internally.
     *
     * @param obj the data object to update in the database.
     * @param con the connection to use
     * @throws TorqueException Any exceptions caught during processing will be
     *         rethrown wrapped into a TorqueException.
     */
    public static void doUpdate(WithdrawnItem obj, Connection con)
        throws TorqueException
    {
        doUpdate(buildCriteria(obj), con);
        obj.setModified(false);
    }

    /**
     * Method to delete.  This method is to be used during a transaction,
     * otherwise use the doDelete(WithdrawnItem) method.  It will take
     * care of the connection details internally.
     *
     * @param obj the data object to delete in the database.
     * @param con the connection to use
     * @throws TorqueException Any exceptions caught during processing will be
     *         rethrown wrapped into a TorqueException.
     */
    public static void doDelete(WithdrawnItem obj, Connection con)
        throws TorqueException
    {
        doDelete(buildCriteria(obj), con);
    }

    /**
     * Method to do deletes.
     *
     * @param pk ObjectKey that is used DELETE from database.
     * @throws TorqueException Any exceptions caught during processing will be
     *         rethrown wrapped into a TorqueException.
     */
    public static void doDelete(ObjectKey pk) throws TorqueException
    {
        BaseWithdrawnItemPeer
           .doDelete(pk, (Connection) null);
    }

    /**
     * Method to delete.  This method is to be used during a transaction,
     * otherwise use the doDelete(ObjectKey) method.  It will take
     * care of the connection details internally.
     *
     * @param pk the primary key for the object to delete in the database.
     * @param con the connection to use
     * @throws TorqueException Any exceptions caught during processing will be
     *         rethrown wrapped into a TorqueException.
     */
    public static void doDelete(ObjectKey pk, Connection con)
        throws TorqueException
    {
        doDelete(buildCriteria(pk), con);
    }

    /** Build a Criteria object from an ObjectKey */
    public static Criteria buildCriteria( ObjectKey pk )
    {
        Criteria criteria = new Criteria();
              criteria.add(WITHDRAWNITEMID, pk);
          return criteria;
     }

    /** Build a Criteria object from the data object for this peer */
    public static Criteria buildCriteria( WithdrawnItem obj )
    {
        Criteria criteria = new Criteria(DATABASE_NAME);
              if (!obj.isNew())
                criteria.add(WITHDRAWNITEMID, obj.getWithdrawnItemId());
                  criteria.add(SELLINGPRICE, obj.getSellingPrice());
                  criteria.add(DATEWITHDRAWN, obj.getDateWithdrawn());
                  criteria.add(REASON, obj.getReason());
                  criteria.add(QUANTITY, obj.getQuantity());
                  criteria.add(DOCTORID, obj.getDoctorId());
                  criteria.add(SALEID, obj.getSaleId());
                  criteria.add(ITEMBATCHID, obj.getItemBatchId());
                  criteria.add(USERID, obj.getUserId());
          return criteria;
    }
 
    
        /**
     * Retrieve a single object by pk
     *
     * @param pk the primary key
     * @throws TorqueException Any exceptions caught during processing will be
     *         rethrown wrapped into a TorqueException.
     * @throws NoRowsException Primary key was not found in database.
     * @throws TooManyRowsException Primary key was not found in database.
     */
    public static WithdrawnItem retrieveByPK(int pk)
        throws TorqueException, NoRowsException, TooManyRowsException
    {
        return retrieveByPK(SimpleKey.keyFor(pk));
    }
  
    /**
     * Retrieve a single object by pk
     *
     * @param pk the primary key
     * @throws TorqueException Any exceptions caught during processing will be
     *         rethrown wrapped into a TorqueException.
     * @throws NoRowsException Primary key was not found in database.
     * @throws TooManyRowsException Primary key was not found in database.
     */
    public static WithdrawnItem retrieveByPK(ObjectKey pk)
        throws TorqueException, NoRowsException, TooManyRowsException
    {
        Connection db = null;
        WithdrawnItem retVal = null;
        try
        {
            db = Torque.getConnection(DATABASE_NAME);
            retVal = retrieveByPK(pk, db);
        }
        finally
        {
            Torque.closeConnection(db);
        }
        return(retVal);
    }

    /**
     * Retrieve a single object by pk
     *
     * @param pk the primary key
     * @param con the connection to use
     * @throws TorqueException Any exceptions caught during processing will be
     *         rethrown wrapped into a TorqueException.
     * @throws NoRowsException Primary key was not found in database.
     * @throws TooManyRowsException Primary key was not found in database.
     */
    public static WithdrawnItem retrieveByPK(ObjectKey pk, Connection con)
        throws TorqueException, NoRowsException, TooManyRowsException
    {
        Criteria criteria = buildCriteria(pk);
        List v = doSelect(criteria, con);
        if (v.size() == 0)
        {
            throw new NoRowsException("Failed to select a row.");
        }
        else if (v.size() > 1)
        {
            throw new TooManyRowsException("Failed to select only one row.");
        }
        else
        {
            return (WithdrawnItem)v.get(0);
        }
    }

    /**
     * Retrieve a multiple objects by pk
     *
     * @param pks List of primary keys
     * @throws TorqueException Any exceptions caught during processing will be
     *         rethrown wrapped into a TorqueException.
     */
    public static List retrieveByPKs(List pks)
        throws TorqueException
    {
        Connection db = null;
        List retVal = null;
        try
        {
           db = Torque.getConnection(DATABASE_NAME);
           retVal = retrieveByPKs(pks, db);
        }
        finally
        {
            Torque.closeConnection(db);
        }
        return(retVal);
    }

    /**
     * Retrieve a multiple objects by pk
     *
     * @param pks List of primary keys
     * @param dbcon the connection to use
     * @throws TorqueException Any exceptions caught during processing will be
     *         rethrown wrapped into a TorqueException.
     */
    public static List retrieveByPKs( List pks, Connection dbcon )
        throws TorqueException
    {
        List objs = null;
        if (pks == null || pks.size() == 0)
        {
            objs = new LinkedList();
        }
        else
        {
            Criteria criteria = new Criteria();
              criteria.addIn( WITHDRAWNITEMID, pks );
          objs = doSelect(criteria, dbcon);
        }
        return objs;
    }

 



                
                                              
                
                

    /**
     * selects a collection of WithdrawnItem objects pre-filled with their
     * Doctor objects.
     *
     * This method is protected by default in order to keep the public
     * api reasonable.  You can provide public methods for those you
     * actually need in WithdrawnItemPeer.
     *
     * @throws TorqueException Any exceptions caught during processing will be
     *         rethrown wrapped into a TorqueException.
     */
    protected static List doSelectJoinDoctor(Criteria c)
        throws TorqueException
    {
        // Set the correct dbName if it has not been overridden
        // c.getDbName will return the same object if not set to
        // another value so == check is okay and faster
        if (c.getDbName() == Torque.getDefaultDB())
        {
            c.setDbName(DATABASE_NAME);
        }

        WithdrawnItemPeer.addSelectColumns(c);
        int offset = numColumns + 1;
        DoctorPeer.addSelectColumns(c);


                        c.addJoin(WithdrawnItemPeer.DOCTORID,
            DoctorPeer.DOCTORID);
        

                                                                                                                                                                          
        List rows = BasePeer.doSelect(c);
        List results = new ArrayList();

        for (int i = 0; i < rows.size(); i++)
        {
            Record row = (Record) rows.get(i);

                            Class omClass = WithdrawnItemPeer.getOMClass();
                    WithdrawnItem obj1 = (WithdrawnItem) WithdrawnItemPeer
                .row2Object(row, 1, omClass);
                     omClass = DoctorPeer.getOMClass();
                    Doctor obj2 = (Doctor)DoctorPeer
                .row2Object(row, offset, omClass);

            boolean newObject = true;
            for (int j = 0; j < results.size(); j++)
            {
                WithdrawnItem temp_obj1 = (WithdrawnItem)results.get(j);
                Doctor temp_obj2 = (Doctor)temp_obj1.getDoctor();
                if (temp_obj2.getPrimaryKey().equals(obj2.getPrimaryKey()))
                {
                    newObject = false;
                    temp_obj2.addWithdrawnItem(obj1);
                    break;
                }
            }
            if (newObject)
            {
                obj2.initWithdrawnItems();
                obj2.addWithdrawnItem(obj1);
            }
            results.add(obj1);
        }
        return results;
    }
                                                            
                
                

    /**
     * selects a collection of WithdrawnItem objects pre-filled with their
     * Sale objects.
     *
     * This method is protected by default in order to keep the public
     * api reasonable.  You can provide public methods for those you
     * actually need in WithdrawnItemPeer.
     *
     * @throws TorqueException Any exceptions caught during processing will be
     *         rethrown wrapped into a TorqueException.
     */
    protected static List doSelectJoinSale(Criteria c)
        throws TorqueException
    {
        // Set the correct dbName if it has not been overridden
        // c.getDbName will return the same object if not set to
        // another value so == check is okay and faster
        if (c.getDbName() == Torque.getDefaultDB())
        {
            c.setDbName(DATABASE_NAME);
        }

        WithdrawnItemPeer.addSelectColumns(c);
        int offset = numColumns + 1;
        SalePeer.addSelectColumns(c);


                        c.addJoin(WithdrawnItemPeer.SALEID,
            SalePeer.SALEID);
        

                                                                                                                                                                          
        List rows = BasePeer.doSelect(c);
        List results = new ArrayList();

        for (int i = 0; i < rows.size(); i++)
        {
            Record row = (Record) rows.get(i);

                            Class omClass = WithdrawnItemPeer.getOMClass();
                    WithdrawnItem obj1 = (WithdrawnItem) WithdrawnItemPeer
                .row2Object(row, 1, omClass);
                     omClass = SalePeer.getOMClass();
                    Sale obj2 = (Sale)SalePeer
                .row2Object(row, offset, omClass);

            boolean newObject = true;
            for (int j = 0; j < results.size(); j++)
            {
                WithdrawnItem temp_obj1 = (WithdrawnItem)results.get(j);
                Sale temp_obj2 = (Sale)temp_obj1.getSale();
                if (temp_obj2.getPrimaryKey().equals(obj2.getPrimaryKey()))
                {
                    newObject = false;
                    temp_obj2.addWithdrawnItem(obj1);
                    break;
                }
            }
            if (newObject)
            {
                obj2.initWithdrawnItems();
                obj2.addWithdrawnItem(obj1);
            }
            results.add(obj1);
        }
        return results;
    }
                                                            
                
                

    /**
     * selects a collection of WithdrawnItem objects pre-filled with their
     * ItemBatch objects.
     *
     * This method is protected by default in order to keep the public
     * api reasonable.  You can provide public methods for those you
     * actually need in WithdrawnItemPeer.
     *
     * @throws TorqueException Any exceptions caught during processing will be
     *         rethrown wrapped into a TorqueException.
     */
    protected static List doSelectJoinItemBatch(Criteria c)
        throws TorqueException
    {
        // Set the correct dbName if it has not been overridden
        // c.getDbName will return the same object if not set to
        // another value so == check is okay and faster
        if (c.getDbName() == Torque.getDefaultDB())
        {
            c.setDbName(DATABASE_NAME);
        }

        WithdrawnItemPeer.addSelectColumns(c);
        int offset = numColumns + 1;
        ItemBatchPeer.addSelectColumns(c);


                        c.addJoin(WithdrawnItemPeer.ITEMBATCHID,
            ItemBatchPeer.ITEMBATCHID);
        

                                                                                                                                                                          
        List rows = BasePeer.doSelect(c);
        List results = new ArrayList();

        for (int i = 0; i < rows.size(); i++)
        {
            Record row = (Record) rows.get(i);

                            Class omClass = WithdrawnItemPeer.getOMClass();
                    WithdrawnItem obj1 = (WithdrawnItem) WithdrawnItemPeer
                .row2Object(row, 1, omClass);
                     omClass = ItemBatchPeer.getOMClass();
                    ItemBatch obj2 = (ItemBatch)ItemBatchPeer
                .row2Object(row, offset, omClass);

            boolean newObject = true;
            for (int j = 0; j < results.size(); j++)
            {
                WithdrawnItem temp_obj1 = (WithdrawnItem)results.get(j);
                ItemBatch temp_obj2 = (ItemBatch)temp_obj1.getItemBatch();
                if (temp_obj2.getPrimaryKey().equals(obj2.getPrimaryKey()))
                {
                    newObject = false;
                    temp_obj2.addWithdrawnItem(obj1);
                    break;
                }
            }
            if (newObject)
            {
                obj2.initWithdrawnItems();
                obj2.addWithdrawnItem(obj1);
            }
            results.add(obj1);
        }
        return results;
    }
                                                            
                
                

    /**
     * selects a collection of WithdrawnItem objects pre-filled with their
     * User objects.
     *
     * This method is protected by default in order to keep the public
     * api reasonable.  You can provide public methods for those you
     * actually need in WithdrawnItemPeer.
     *
     * @throws TorqueException Any exceptions caught during processing will be
     *         rethrown wrapped into a TorqueException.
     */
    protected static List doSelectJoinUser(Criteria c)
        throws TorqueException
    {
        // Set the correct dbName if it has not been overridden
        // c.getDbName will return the same object if not set to
        // another value so == check is okay and faster
        if (c.getDbName() == Torque.getDefaultDB())
        {
            c.setDbName(DATABASE_NAME);
        }

        WithdrawnItemPeer.addSelectColumns(c);
        int offset = numColumns + 1;
        UserPeer.addSelectColumns(c);


                        c.addJoin(WithdrawnItemPeer.USERID,
            UserPeer.USERID);
        

                                                                                                                                                                          
        List rows = BasePeer.doSelect(c);
        List results = new ArrayList();

        for (int i = 0; i < rows.size(); i++)
        {
            Record row = (Record) rows.get(i);

                            Class omClass = WithdrawnItemPeer.getOMClass();
                    WithdrawnItem obj1 = (WithdrawnItem) WithdrawnItemPeer
                .row2Object(row, 1, omClass);
                     omClass = UserPeer.getOMClass();
                    User obj2 = (User)UserPeer
                .row2Object(row, offset, omClass);

            boolean newObject = true;
            for (int j = 0; j < results.size(); j++)
            {
                WithdrawnItem temp_obj1 = (WithdrawnItem)results.get(j);
                User temp_obj2 = (User)temp_obj1.getUser();
                if (temp_obj2.getPrimaryKey().equals(obj2.getPrimaryKey()))
                {
                    newObject = false;
                    temp_obj2.addWithdrawnItem(obj1);
                    break;
                }
            }
            if (newObject)
            {
                obj2.initWithdrawnItems();
                obj2.addWithdrawnItem(obj1);
            }
            results.add(obj1);
        }
        return results;
    }
                    
  
                                              
          
        
                                  
                

    /**
     * selects a collection of WithdrawnItem objects pre-filled with
     * all related objects.
     *
     * This method is protected by default in order to keep the public
     * api reasonable.  You can provide public methods for those you
     * actually need in WithdrawnItemPeer.
     *
     * @throws TorqueException Any exceptions caught during processing will be
     *         rethrown wrapped into a TorqueException.
     */
    protected static List doSelectJoinAllExceptDoctor(Criteria c)
        throws TorqueException
    {
        // Set the correct dbName if it has not been overridden
        // c.getDbName will return the same object if not set to another value
        // so == check is okay and faster
        if (c.getDbName() == Torque.getDefaultDB())
        {
            c.setDbName(DATABASE_NAME);
        }

        addSelectColumns(c);
        int offset2 = numColumns + 1;
                                    
                                                  
                    SalePeer.addSelectColumns(c);
        int offset3 = offset2 + SalePeer.numColumns;
                                                                
                    ItemBatchPeer.addSelectColumns(c);
        int offset4 = offset3 + ItemBatchPeer.numColumns;
                                                                
                    UserPeer.addSelectColumns(c);
        int offset5 = offset4 + UserPeer.numColumns;
                                                                                                                                                                                                                      
        List rows = BasePeer.doSelect(c);
        List results = new ArrayList();

        for (int i = 0; i < rows.size(); i++)
        {
            Record row = (Record)rows.get(i);

                            Class omClass = WithdrawnItemPeer.getOMClass();
                    WithdrawnItem obj1 = (WithdrawnItem)WithdrawnItemPeer
                .row2Object(row, 1, omClass);
                                                
                                                                  
                                                        
                            
              
                           omClass = SalePeer.getOMClass();
                          Sale obj2 = (Sale)SalePeer
                .row2Object( row, offset2, omClass);

               boolean  newObject = true;
            for (int j = 0; j < results.size(); j++)
            {
                WithdrawnItem temp_obj1 = (WithdrawnItem)results.get(j);
                Sale temp_obj2 = (Sale)temp_obj1.getSale();
                if (temp_obj2.getPrimaryKey().equals(obj2.getPrimaryKey()))
                {
                    newObject = false;
                    temp_obj2.addWithdrawnItem(obj1);
                    break;
                }
            }
            if (newObject)
            {
                obj2.initWithdrawnItems();
                obj2.addWithdrawnItem(obj1);
            }
                                                                    
                                                        
                            
              
                           omClass = ItemBatchPeer.getOMClass();
                          ItemBatch obj3 = (ItemBatch)ItemBatchPeer
                .row2Object( row, offset3, omClass);

               newObject = true;
            for (int j = 0; j < results.size(); j++)
            {
                WithdrawnItem temp_obj1 = (WithdrawnItem)results.get(j);
                ItemBatch temp_obj3 = (ItemBatch)temp_obj1.getItemBatch();
                if (temp_obj3.getPrimaryKey().equals(obj3.getPrimaryKey()))
                {
                    newObject = false;
                    temp_obj3.addWithdrawnItem(obj1);
                    break;
                }
            }
            if (newObject)
            {
                obj3.initWithdrawnItems();
                obj3.addWithdrawnItem(obj1);
            }
                                                                    
                                                        
                            
              
                           omClass = UserPeer.getOMClass();
                          User obj4 = (User)UserPeer
                .row2Object( row, offset4, omClass);

               newObject = true;
            for (int j = 0; j < results.size(); j++)
            {
                WithdrawnItem temp_obj1 = (WithdrawnItem)results.get(j);
                User temp_obj4 = (User)temp_obj1.getUser();
                if (temp_obj4.getPrimaryKey().equals(obj4.getPrimaryKey()))
                {
                    newObject = false;
                    temp_obj4.addWithdrawnItem(obj1);
                    break;
                }
            }
            if (newObject)
            {
                obj4.initWithdrawnItems();
                obj4.addWithdrawnItem(obj1);
            }
                                                results.add(obj1);
        }
        return results;
    }
        
        
                                  
                

    /**
     * selects a collection of WithdrawnItem objects pre-filled with
     * all related objects.
     *
     * This method is protected by default in order to keep the public
     * api reasonable.  You can provide public methods for those you
     * actually need in WithdrawnItemPeer.
     *
     * @throws TorqueException Any exceptions caught during processing will be
     *         rethrown wrapped into a TorqueException.
     */
    protected static List doSelectJoinAllExceptSale(Criteria c)
        throws TorqueException
    {
        // Set the correct dbName if it has not been overridden
        // c.getDbName will return the same object if not set to another value
        // so == check is okay and faster
        if (c.getDbName() == Torque.getDefaultDB())
        {
            c.setDbName(DATABASE_NAME);
        }

        addSelectColumns(c);
        int offset2 = numColumns + 1;
                                    
                    DoctorPeer.addSelectColumns(c);
        int offset3 = offset2 + DoctorPeer.numColumns;
                                                                
                                                  
                    ItemBatchPeer.addSelectColumns(c);
        int offset4 = offset3 + ItemBatchPeer.numColumns;
                                                                
                    UserPeer.addSelectColumns(c);
        int offset5 = offset4 + UserPeer.numColumns;
                                                                                                                                                                                                                      
        List rows = BasePeer.doSelect(c);
        List results = new ArrayList();

        for (int i = 0; i < rows.size(); i++)
        {
            Record row = (Record)rows.get(i);

                            Class omClass = WithdrawnItemPeer.getOMClass();
                    WithdrawnItem obj1 = (WithdrawnItem)WithdrawnItemPeer
                .row2Object(row, 1, omClass);
                                                
                                                        
                            
              
                           omClass = DoctorPeer.getOMClass();
                          Doctor obj2 = (Doctor)DoctorPeer
                .row2Object( row, offset2, omClass);

               boolean  newObject = true;
            for (int j = 0; j < results.size(); j++)
            {
                WithdrawnItem temp_obj1 = (WithdrawnItem)results.get(j);
                Doctor temp_obj2 = (Doctor)temp_obj1.getDoctor();
                if (temp_obj2.getPrimaryKey().equals(obj2.getPrimaryKey()))
                {
                    newObject = false;
                    temp_obj2.addWithdrawnItem(obj1);
                    break;
                }
            }
            if (newObject)
            {
                obj2.initWithdrawnItems();
                obj2.addWithdrawnItem(obj1);
            }
                                                                    
                                                                  
                                                        
                            
              
                           omClass = ItemBatchPeer.getOMClass();
                          ItemBatch obj3 = (ItemBatch)ItemBatchPeer
                .row2Object( row, offset3, omClass);

               newObject = true;
            for (int j = 0; j < results.size(); j++)
            {
                WithdrawnItem temp_obj1 = (WithdrawnItem)results.get(j);
                ItemBatch temp_obj3 = (ItemBatch)temp_obj1.getItemBatch();
                if (temp_obj3.getPrimaryKey().equals(obj3.getPrimaryKey()))
                {
                    newObject = false;
                    temp_obj3.addWithdrawnItem(obj1);
                    break;
                }
            }
            if (newObject)
            {
                obj3.initWithdrawnItems();
                obj3.addWithdrawnItem(obj1);
            }
                                                                    
                                                        
                            
              
                           omClass = UserPeer.getOMClass();
                          User obj4 = (User)UserPeer
                .row2Object( row, offset4, omClass);

               newObject = true;
            for (int j = 0; j < results.size(); j++)
            {
                WithdrawnItem temp_obj1 = (WithdrawnItem)results.get(j);
                User temp_obj4 = (User)temp_obj1.getUser();
                if (temp_obj4.getPrimaryKey().equals(obj4.getPrimaryKey()))
                {
                    newObject = false;
                    temp_obj4.addWithdrawnItem(obj1);
                    break;
                }
            }
            if (newObject)
            {
                obj4.initWithdrawnItems();
                obj4.addWithdrawnItem(obj1);
            }
                                                results.add(obj1);
        }
        return results;
    }
        
        
                                  
                

    /**
     * selects a collection of WithdrawnItem objects pre-filled with
     * all related objects.
     *
     * This method is protected by default in order to keep the public
     * api reasonable.  You can provide public methods for those you
     * actually need in WithdrawnItemPeer.
     *
     * @throws TorqueException Any exceptions caught during processing will be
     *         rethrown wrapped into a TorqueException.
     */
    protected static List doSelectJoinAllExceptItemBatch(Criteria c)
        throws TorqueException
    {
        // Set the correct dbName if it has not been overridden
        // c.getDbName will return the same object if not set to another value
        // so == check is okay and faster
        if (c.getDbName() == Torque.getDefaultDB())
        {
            c.setDbName(DATABASE_NAME);
        }

        addSelectColumns(c);
        int offset2 = numColumns + 1;
                                    
                    DoctorPeer.addSelectColumns(c);
        int offset3 = offset2 + DoctorPeer.numColumns;
                                                                
                    SalePeer.addSelectColumns(c);
        int offset4 = offset3 + SalePeer.numColumns;
                                                                
                                                  
                    UserPeer.addSelectColumns(c);
        int offset5 = offset4 + UserPeer.numColumns;
                                                                                                                                                                                                                      
        List rows = BasePeer.doSelect(c);
        List results = new ArrayList();

        for (int i = 0; i < rows.size(); i++)
        {
            Record row = (Record)rows.get(i);

                            Class omClass = WithdrawnItemPeer.getOMClass();
                    WithdrawnItem obj1 = (WithdrawnItem)WithdrawnItemPeer
                .row2Object(row, 1, omClass);
                                                
                                                        
                            
              
                           omClass = DoctorPeer.getOMClass();
                          Doctor obj2 = (Doctor)DoctorPeer
                .row2Object( row, offset2, omClass);

               boolean  newObject = true;
            for (int j = 0; j < results.size(); j++)
            {
                WithdrawnItem temp_obj1 = (WithdrawnItem)results.get(j);
                Doctor temp_obj2 = (Doctor)temp_obj1.getDoctor();
                if (temp_obj2.getPrimaryKey().equals(obj2.getPrimaryKey()))
                {
                    newObject = false;
                    temp_obj2.addWithdrawnItem(obj1);
                    break;
                }
            }
            if (newObject)
            {
                obj2.initWithdrawnItems();
                obj2.addWithdrawnItem(obj1);
            }
                                                                    
                                                        
                            
              
                           omClass = SalePeer.getOMClass();
                          Sale obj3 = (Sale)SalePeer
                .row2Object( row, offset3, omClass);

               newObject = true;
            for (int j = 0; j < results.size(); j++)
            {
                WithdrawnItem temp_obj1 = (WithdrawnItem)results.get(j);
                Sale temp_obj3 = (Sale)temp_obj1.getSale();
                if (temp_obj3.getPrimaryKey().equals(obj3.getPrimaryKey()))
                {
                    newObject = false;
                    temp_obj3.addWithdrawnItem(obj1);
                    break;
                }
            }
            if (newObject)
            {
                obj3.initWithdrawnItems();
                obj3.addWithdrawnItem(obj1);
            }
                                                                    
                                                                  
                                                        
                            
              
                           omClass = UserPeer.getOMClass();
                          User obj4 = (User)UserPeer
                .row2Object( row, offset4, omClass);

               newObject = true;
            for (int j = 0; j < results.size(); j++)
            {
                WithdrawnItem temp_obj1 = (WithdrawnItem)results.get(j);
                User temp_obj4 = (User)temp_obj1.getUser();
                if (temp_obj4.getPrimaryKey().equals(obj4.getPrimaryKey()))
                {
                    newObject = false;
                    temp_obj4.addWithdrawnItem(obj1);
                    break;
                }
            }
            if (newObject)
            {
                obj4.initWithdrawnItems();
                obj4.addWithdrawnItem(obj1);
            }
                                                results.add(obj1);
        }
        return results;
    }
        
        
                                  
                

    /**
     * selects a collection of WithdrawnItem objects pre-filled with
     * all related objects.
     *
     * This method is protected by default in order to keep the public
     * api reasonable.  You can provide public methods for those you
     * actually need in WithdrawnItemPeer.
     *
     * @throws TorqueException Any exceptions caught during processing will be
     *         rethrown wrapped into a TorqueException.
     */
    protected static List doSelectJoinAllExceptUser(Criteria c)
        throws TorqueException
    {
        // Set the correct dbName if it has not been overridden
        // c.getDbName will return the same object if not set to another value
        // so == check is okay and faster
        if (c.getDbName() == Torque.getDefaultDB())
        {
            c.setDbName(DATABASE_NAME);
        }

        addSelectColumns(c);
        int offset2 = numColumns + 1;
                                    
                    DoctorPeer.addSelectColumns(c);
        int offset3 = offset2 + DoctorPeer.numColumns;
                                                                
                    SalePeer.addSelectColumns(c);
        int offset4 = offset3 + SalePeer.numColumns;
                                                                
                    ItemBatchPeer.addSelectColumns(c);
        int offset5 = offset4 + ItemBatchPeer.numColumns;
                                                                
                                                                                                                                                                                                        
        List rows = BasePeer.doSelect(c);
        List results = new ArrayList();

        for (int i = 0; i < rows.size(); i++)
        {
            Record row = (Record)rows.get(i);

                            Class omClass = WithdrawnItemPeer.getOMClass();
                    WithdrawnItem obj1 = (WithdrawnItem)WithdrawnItemPeer
                .row2Object(row, 1, omClass);
                                                
                                                        
                            
              
                           omClass = DoctorPeer.getOMClass();
                          Doctor obj2 = (Doctor)DoctorPeer
                .row2Object( row, offset2, omClass);

               boolean  newObject = true;
            for (int j = 0; j < results.size(); j++)
            {
                WithdrawnItem temp_obj1 = (WithdrawnItem)results.get(j);
                Doctor temp_obj2 = (Doctor)temp_obj1.getDoctor();
                if (temp_obj2.getPrimaryKey().equals(obj2.getPrimaryKey()))
                {
                    newObject = false;
                    temp_obj2.addWithdrawnItem(obj1);
                    break;
                }
            }
            if (newObject)
            {
                obj2.initWithdrawnItems();
                obj2.addWithdrawnItem(obj1);
            }
                                                                    
                                                        
                            
              
                           omClass = SalePeer.getOMClass();
                          Sale obj3 = (Sale)SalePeer
                .row2Object( row, offset3, omClass);

               newObject = true;
            for (int j = 0; j < results.size(); j++)
            {
                WithdrawnItem temp_obj1 = (WithdrawnItem)results.get(j);
                Sale temp_obj3 = (Sale)temp_obj1.getSale();
                if (temp_obj3.getPrimaryKey().equals(obj3.getPrimaryKey()))
                {
                    newObject = false;
                    temp_obj3.addWithdrawnItem(obj1);
                    break;
                }
            }
            if (newObject)
            {
                obj3.initWithdrawnItems();
                obj3.addWithdrawnItem(obj1);
            }
                                                                    
                                                        
                            
              
                           omClass = ItemBatchPeer.getOMClass();
                          ItemBatch obj4 = (ItemBatch)ItemBatchPeer
                .row2Object( row, offset4, omClass);

               newObject = true;
            for (int j = 0; j < results.size(); j++)
            {
                WithdrawnItem temp_obj1 = (WithdrawnItem)results.get(j);
                ItemBatch temp_obj4 = (ItemBatch)temp_obj1.getItemBatch();
                if (temp_obj4.getPrimaryKey().equals(obj4.getPrimaryKey()))
                {
                    newObject = false;
                    temp_obj4.addWithdrawnItem(obj1);
                    break;
                }
            }
            if (newObject)
            {
                obj4.initWithdrawnItems();
                obj4.addWithdrawnItem(obj1);
            }
                                                                    
                                              results.add(obj1);
        }
        return results;
    }
                    
  
      /**
     * Returns the TableMap related to this peer.  This method is not
     * needed for general use but a specific application could have a need.
     *
     * @throws TorqueException Any exceptions caught during processing will be
     *         rethrown wrapped into a TorqueException.
     */
    protected static TableMap getTableMap()
        throws TorqueException
    {
        return Torque.getDatabaseMap(DATABASE_NAME).getTable(TABLE_NAME);
    }
   }
