package winnu.dao;


import java.math.BigDecimal;
import java.sql.Connection;
import java.util.ArrayList;
import java.util.Date;
import java.util.Collections;
import java.util.List;

import org.apache.commons.lang.ObjectUtils;
import org.apache.torque.TorqueException;
import org.apache.torque.om.BaseObject;
import org.apache.torque.om.ComboKey;
import org.apache.torque.om.DateKey;
import org.apache.torque.om.NumberKey;
import org.apache.torque.om.ObjectKey;
import org.apache.torque.om.SimpleKey;
import org.apache.torque.om.StringKey;
import org.apache.torque.om.Persistent;
import org.apache.torque.util.Criteria;
import org.apache.torque.util.Transaction;

  
  
/**
 * This class was autogenerated by Torque on:
 *
 * [Mon Mar 22 12:48:49 SGT 2010]
 *
 * You should not use this class directly.  It should not even be
 * extended all references should be to StockedItem
 */
public abstract class BaseStockedItem extends BaseObject
{
    /** The Peer class */
    private static final StockedItemPeer peer =
        new StockedItemPeer();

        
    /** The value for the stockedItemId field */
    private int stockedItemId;
      
    /** The value for the currentPrice field */
    private double currentPrice;
      
    /** The value for the quantity field */
    private int quantity;
      
    /** The value for the itemBatchId field */
    private int itemBatchId;
  
    
    /**
     * Get the StockedItemId
     *
     * @return int
     */
    public int getStockedItemId()
    {
        return stockedItemId;
    }

                        
    /**
     * Set the value of StockedItemId
     *
     * @param v new value
     */
    public void setStockedItemId(int v) 
    {
    
                  if (this.stockedItemId != v)
              {
            this.stockedItemId = v;
            setModified(true);
        }
    
          
              }
  
    /**
     * Get the CurrentPrice
     *
     * @return double
     */
    public double getCurrentPrice()
    {
        return currentPrice;
    }

                        
    /**
     * Set the value of CurrentPrice
     *
     * @param v new value
     */
    public void setCurrentPrice(double v) 
    {
    
                  if (this.currentPrice != v)
              {
            this.currentPrice = v;
            setModified(true);
        }
    
          
              }
  
    /**
     * Get the Quantity
     *
     * @return int
     */
    public int getQuantity()
    {
        return quantity;
    }

                        
    /**
     * Set the value of Quantity
     *
     * @param v new value
     */
    public void setQuantity(int v) 
    {
    
                  if (this.quantity != v)
              {
            this.quantity = v;
            setModified(true);
        }
    
          
              }
  
    /**
     * Get the ItemBatchId
     *
     * @return int
     */
    public int getItemBatchId()
    {
        return itemBatchId;
    }

                              
    /**
     * Set the value of ItemBatchId
     *
     * @param v new value
     */
    public void setItemBatchId(int v) throws TorqueException
    {
    
                  if (this.itemBatchId != v)
              {
            this.itemBatchId = v;
            setModified(true);
        }
    
                          
                if (aItemBatch != null && !(aItemBatch.getItemBatchId() == v))
                {
            aItemBatch = null;
        }
      
              }
  
      
    
                  
    
        private ItemBatch aItemBatch;

    /**
     * Declares an association between this object and a ItemBatch object
     *
     * @param v ItemBatch
     * @throws TorqueException
     */
    public void setItemBatch(ItemBatch v) throws TorqueException
    {
            if (v == null)
        {
                    setItemBatchId(0);
                  }
        else
        {
            setItemBatchId(v.getItemBatchId());
        }
                aItemBatch = v;
    }

                                            
    /**
     * Get the associated ItemBatch object
     *
     * @return the associated ItemBatch object
     * @throws TorqueException
     */
    public ItemBatch getItemBatch() throws TorqueException
    {
        if (aItemBatch == null && (this.itemBatchId > 0))
        {
                          aItemBatch = ItemBatchPeer.retrieveByPK(SimpleKey.keyFor(this.itemBatchId));
              
            /* The following can be used instead of the line above to
               guarantee the related object contains a reference
               to this object, but this level of coupling
               may be undesirable in many circumstances.
               As it can lead to a db query with many results that may
               never be used.
               ItemBatch obj = ItemBatchPeer.retrieveByPK(this.itemBatchId);
               obj.addStockedItems(this);
            */
        }
        return aItemBatch;
    }

    /**
     * Provides convenient way to set a relationship based on a
     * ObjectKey.  e.g.
     * <code>bar.setFooKey(foo.getPrimaryKey())</code>
     *
           */
    public void setItemBatchKey(ObjectKey key) throws TorqueException
    {
      
                        setItemBatchId(((NumberKey) key).intValue());
                  }
       
                
    private static List fieldNames = null;

    /**
     * Generate a list of field names.
     *
     * @return a list of field names
     */
    public static synchronized List getFieldNames()
    {
        if (fieldNames == null)
        {
            fieldNames = new ArrayList();
              fieldNames.add("StockedItemId");
              fieldNames.add("CurrentPrice");
              fieldNames.add("Quantity");
              fieldNames.add("ItemBatchId");
              fieldNames = Collections.unmodifiableList(fieldNames);
        }
        return fieldNames;
    }

    /**
     * Retrieves a field from the object by name passed in as a String.
     *
     * @param name field name
     * @return value
     */
    public Object getByName(String name)
    {
          if (name.equals("StockedItemId"))
        {
                return new Integer(getStockedItemId());
            }
          if (name.equals("CurrentPrice"))
        {
                return new Double(getCurrentPrice());
            }
          if (name.equals("Quantity"))
        {
                return new Integer(getQuantity());
            }
          if (name.equals("ItemBatchId"))
        {
                return new Integer(getItemBatchId());
            }
          return null;
    }
    
    /**
     * Retrieves a field from the object by name passed in
     * as a String.  The String must be one of the static
     * Strings defined in this Class' Peer.
     *
     * @param name peer name
     * @return value
     */
    public Object getByPeerName(String name)
    {
          if (name.equals(StockedItemPeer.STOCKEDITEMID))
        {
                return new Integer(getStockedItemId());
            }
          if (name.equals(StockedItemPeer.CURRENTPRICE))
        {
                return new Double(getCurrentPrice());
            }
          if (name.equals(StockedItemPeer.QUANTITY))
        {
                return new Integer(getQuantity());
            }
          if (name.equals(StockedItemPeer.ITEMBATCHID))
        {
                return new Integer(getItemBatchId());
            }
          return null;
    }

    /**
     * Retrieves a field from the object by Position as specified
     * in the xml schema.  Zero-based.
     *
     * @param pos position in xml schema
     * @return value
     */
    public Object getByPosition(int pos)
    {
            if (pos == 0)
        {
                return new Integer(getStockedItemId());
            }
              if (pos == 1)
        {
                return new Double(getCurrentPrice());
            }
              if (pos == 2)
        {
                return new Integer(getQuantity());
            }
              if (pos == 3)
        {
                return new Integer(getItemBatchId());
            }
              return null;
    }
     
    /**
     * Stores the object in the database.  If the object is new,
     * it inserts it; otherwise an update is performed.
     *
     * @throws Exception
     */
    public void save() throws Exception
    {
          save(StockedItemPeer.getMapBuilder()
                .getDatabaseMap().getName());
      }

    /**
     * Stores the object in the database.  If the object is new,
     * it inserts it; otherwise an update is performed.
       * Note: this code is here because the method body is
     * auto-generated conditionally and therefore needs to be
     * in this file instead of in the super class, BaseObject.
       *
     * @param dbName
     * @throws TorqueException
     */
    public void save(String dbName) throws TorqueException
    {
        Connection con = null;
          try
        {
            con = Transaction.begin(dbName);
            save(con);
            Transaction.commit(con);
        }
        catch(TorqueException e)
        {
            Transaction.safeRollback(con);
            throw e;
        }
      }

      /** flag to prevent endless save loop, if this object is referenced
        by another object which falls in this transaction. */
    private boolean alreadyInSave = false;
      /**
     * Stores the object in the database.  If the object is new,
     * it inserts it; otherwise an update is performed.  This method
     * is meant to be used as part of a transaction, otherwise use
     * the save() method and the connection details will be handled
     * internally
     *
     * @param con
     * @throws TorqueException
     */
    public void save(Connection con) throws TorqueException
    {
          if (!alreadyInSave)
        {
            alreadyInSave = true;


  
            // If this object has been modified, then save it to the database.
            if (isModified())
            {
                if (isNew())
                {
                    StockedItemPeer.doInsert((StockedItem) this, con);
                    setNew(false);
                }
                else
                {
                    StockedItemPeer.doUpdate((StockedItem) this, con);
                }
            }

                      alreadyInSave = false;
        }
      }


                    
      /**
     * Set the PrimaryKey using ObjectKey.
     *
     * @param  stockedItemId ObjectKey
     */
    public void setPrimaryKey(ObjectKey key)
        
    {
            setStockedItemId(((NumberKey) key).intValue());
        }

    /**
     * Set the PrimaryKey using a String.
     *
     * @param key
     */
    public void setPrimaryKey(String key) 
    {
            setStockedItemId(Integer.parseInt(key));
        }

  
    /**
     * returns an id that differentiates this object from others
     * of its class.
     */
    public ObjectKey getPrimaryKey()
    {
          return SimpleKey.keyFor(getStockedItemId());
      }

 

    /**
     * Makes a copy of this object.
     * It creates a new object filling in the simple attributes.
       * It then fills all the association collections and sets the
     * related objects to isNew=true.
       */
      public StockedItem copy() throws TorqueException
    {
        return copyInto(new StockedItem());
    }
  
    protected StockedItem copyInto(StockedItem copyObj) throws TorqueException
    {
          copyObj.setStockedItemId(stockedItemId);
          copyObj.setCurrentPrice(currentPrice);
          copyObj.setQuantity(quantity);
          copyObj.setItemBatchId(itemBatchId);
  
                    copyObj.setStockedItemId(0);
                              
        
        return copyObj;
    }

    /**
     * returns a peer instance associated with this om.  Since Peer classes
     * are not to have any instance attributes, this method returns the
     * same instance for all member of this class. The method could therefore
     * be static, but this would prevent one from overriding the behavior.
     */
    public StockedItemPeer getPeer()
    {
        return peer;
    }

    public String toString()
    {
        StringBuffer str = new StringBuffer();
        str.append("StockedItem:\n");
        str.append("StockedItemId = ")
           .append(getStockedItemId())
           .append("\n");
        str.append("CurrentPrice = ")
           .append(getCurrentPrice())
           .append("\n");
        str.append("Quantity = ")
           .append(getQuantity())
           .append("\n");
        str.append("ItemBatchId = ")
           .append(getItemBatchId())
           .append("\n");
        return(str.toString());
    }
}
