
package winnu.dao;


import org.apache.torque.om.Persistent;

/**
 * The skeleton for this class was autogenerated by Torque on:
 *
 * [Mon Feb 15 20:18:02 SGT 2010]
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 */
@SuppressWarnings("serial")
public  class Sale
    extends winnu.dao.BaseSale
    implements Persistent
{
}
