
package winnu.dao;


import org.apache.torque.om.Persistent;

/**
 * The skeleton for this class was autogenerated by Torque on:
 *
 * [Tue Feb 09 20:51:03 SGT 2010]
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 */
@SuppressWarnings("serial")
public  class User
    extends winnu.dao.BaseUser
    implements Persistent
{
}
